const express = require("express")
const router = express.Router()
const inventoryController = require("../controllers/inventoryController")
const validate = require("../utilities/inventory-validation")
const utilities = require("../utilities/")

router.get("/type/:classification_id", inventoryController.buildVehicleList)
router.get("/detail/:inv_id", inventoryController.buildVehicleDetail)
router.get("/management", utilities.requireEmployeeOrAdmin, inventoryController.buildVehicleManagement)
router.get("/add-classification", utilities.requireEmployeeOrAdmin, inventoryController.buildAddClassification)
router.post("/add-classification", utilities.requireEmployeeOrAdmin, validate.addClassificationRules(), validate.checkAddClassificationData, inventoryController.addClassification)
router.get("/add-inventory", utilities.requireEmployeeOrAdmin, inventoryController.buildAddInventory)
router.post("/add-inventory", utilities.requireEmployeeOrAdmin, validate.addInventoryRules(), validate.checkAddInventoryData, inventoryController.addInventory)
router.get("/getInventory/:classification_id", inventoryController.getInventoryJSON)
router.get("/edit/:inv_id", utilities.requireEmployeeOrAdmin, inventoryController.buildEditInventory)
router.post("/edit-inventory", utilities.requireEmployeeOrAdmin, validate.addInventoryRules(), validate.checkEditInventoryData, inventoryController.updateInventory)
router.get("/delete/:inv_id", utilities.requireEmployeeOrAdmin, inventoryController.buildDeleteInventory)
router.post("/delete-inventory", utilities.requireEmployeeOrAdmin, inventoryController.deleteInventory)

module.exports = router